Algoritmo "semnome"
// Disciplina   :  [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/01/2017
Var
   Contador: Inteiro
Inicio
   Contador <- 0
   Enquanto (Contador < 10) faca
      Contador <- Contador + 1
      EscrevaL(Contador)
   FimEnquanto


Fimalgoritmo