algoritmo "ConversãoCelsiusFahrenheit"
// Função :
// Autor : deomorxsy
// Data : 06/01/2016
// Seção de Declarações 
var
   Grau_Celsius, Grau_Fahrenheit:Real
inicio
      Escreval("Informe um valor de temperatura para Grau Celsius")
      Leia(Grau_Celsius)
      Grau_Fahrenheit <- (Grau_Celsius*1.8+32)
      Escreval("O correspondente da temperatura Celsius informada, em Fahrenheit, é ", Grau_Fahrenheit)
fimalgoritmo
