Algoritmo "semnome"
// Disciplina   :  [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Otaquisse inacabada.
// Autor(a)    : deomorxsy
// Data atual  : 25/01/2017
Var
   contador: inteiro


Inicio
   contador <- 1000
   Enquanto (contador >= 0) faca
      EscrevaL("Contador - Quanto é mil menos sete?")
      EscrevaL(contador)
      contador <- contador - 7
   FimEnquanto


Fimalgoritmo